import fetch from "node-fetch";

export default {
  name: "imagine",
  description: "Generate an AI image using Pollinations API (Free, No Key)",
  async execute(sock, msg, args) {
    const from = msg.key.remoteJid;
    const prompt = args.join(" ");

    if (!prompt) {
      return sock.sendMessage(
        from,
        {
          text: `
🎨 *AI Image Generator - NexOra*

💡 Usage:
.imagine <prompt>

🧠 Example:
.imagine a cyberpunk fox wearing sunglasses
          `.trim(),
        },
        { quoted: msg }
      );
    }

    const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}`;

    await sock.sendMessage(
      from,
      {
        image: { url: imageUrl },
        caption: `
✨ *AI Image Generated by NexOra 🤖*
🧠 Prompt: ${prompt}
🌐 Source: NexOra 
        `.trim(),
      },
      { quoted: msg }
    );
  },
};
