export default {
  name: "image",
  aliases: ["aiimage", "genimage", "img"],
  description: "Generate AI images using Pollinations API (free)",
  
  async execute(sock, msg, args, from) {
    const prompt = args.join(" ");
    if (!prompt)
      return sock.sendMessage(from, { text: "💡 Usage: .image <prompt>" }, { quoted: msg });

    const variations = 3; // how many versions to generate
    const basePrompt = encodeURIComponent(prompt);

    let responseText = `🎨 *NexOra Image Generator*\nPrompt: _${prompt}_\n\nGenerating ${variations} variations...`;

    await sock.sendMessage(from, { text: responseText }, { quoted: msg });

    for (let i = 0; i < variations; i++) {
      const style = Math.floor(Math.random() * 10); // random style seed
      const imageUrl = `https://image.pollinations.ai/prompt/${basePrompt}%20style=${style}`;

      await sock.sendMessage(
        from,
        {
          image: { url: imageUrl },
          caption: `🖼️ Variation ${i + 1}\n🎨 *Prompt:* ${prompt}\n🧠 Generated by *NexOra AI*`,
        },
        { quoted: msg }
      );
    }
  },
};
