// commands/textlogo.js
import mumaker from "mumaker";

export default {
  name: "textlogo",
  description: "Generate stylish text logos with various effects",

  async execute(sock, msg, args) {
    const type = args[0];
    const text = args.slice(1).join(" ");

    if (!type || !text) {
      return await sock.sendMessage(msg.key.remoteJid, {
        text: `❗Usage: .textlogo fire NexOra\n\nOr directly use:\n.fire NexOra\n.neon Shadow\n.metallic King`,
      });
    }

    // List of available effects
    const textEffects = {
      metallic: "https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html",
      ice: "https://en.ephoto360.com/ice-text-effect-online-101.html",
      snow: "https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html",
      impressive: "https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html",
      matrix: "https://en.ephoto360.com/matrix-text-effect-154.html",
      light: "https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html",
      neon: "https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html",
      devil: "https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html",
      purple: "https://en.ephoto360.com/purple-text-effect-online-100.html",
      thunder: "https://en.ephoto360.com/thunder-text-effect-online-97.html",
      leaves: "https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html",
      "1917": "https://en.ephoto360.com/1917-style-text-effect-523.html",
      arena: "https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html",
      hacker: "https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html",
      sand: "https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html",
      blackpink: "https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html",
      glitch: "https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html",
      fire: "https://en.ephoto360.com/flame-lettering-effect-372.html",
    };

    // Check for invalid type
    if (!textEffects[type]) {
      return await sock.sendMessage(msg.key.remoteJid, {
        text: `⚠️ Invalid effect type!\nAvailable: ${Object.keys(textEffects).join(", ")}`,
      });
    }

    try {
      const result = await mumaker.ephoto(textEffects[type], text);
      await sock.sendMessage(msg.key.remoteJid, {
        image: { url: result.image },
        caption: `✨ *${type.toUpperCase()} Text Logo Created!*\n\nGenerated by NexOra Bot 🚀`,
      });
    } catch (err) {
      console.error("❌ Textlogo error:", err);
      await sock.sendMessage(msg.key.remoteJid, {
        text: "⚠️ Failed to generate text logo. Try again later.",
      });
    }
  },
};

// 🔁 These are shortcuts so user can use .fire, .neon, etc.
export const aliases = [
  "metallic", "ice", "snow", "impressive", "matrix", "light",
  "neon", "devil", "purple", "thunder", "leaves", "1917",
  "arena", "hacker", "sand", "blackpink", "glitch", "fire"
];
