import mumaker from "mumaker";

const ephotoLinks = {
  metallic: "https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html",
  ice: "https://en.ephoto360.com/ice-text-effect-online-101.html",
  snow: "https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html",
  impressive: "https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html",
  matrix: "https://en.ephoto360.com/matrix-text-effect-154.html",
  light: "https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html",
  neon: "https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html",
  devil: "https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html",
  purple: "https://en.ephoto360.com/purple-text-effect-online-100.html",
  thunder: "https://en.ephoto360.com/thunder-text-effect-online-97.html",
  leaves: "https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html",
  "1917": "https://en.ephoto360.com/1917-style-text-effect-523.html",
  arena: "https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html",
  hacker: "https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html",
  sand: "https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html",
  blackpink: "https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html",
  glitch: "https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html",
  fire: "https://en.ephoto360.com/flame-lettering-effect-372.html",
};

export default {
  name: "textlogo",
  description: "Generate styled text logos using ephoto360 effects",
  async execute(sock, msg, args) {
    try {
      const [type, ...rest] = args;
      const text = rest.join(" ").trim();

      if (!type || !text)
        return sock.sendMessage(
          msg.key.remoteJid,
          { text: "❌ Usage: .metallic NexOra" },
          { quoted: msg }
        );

      const url = ephotoLinks[type.toLowerCase()];
      if (!url)
        return sock.sendMessage(
          msg.key.remoteJid,
          { text: "⚠️ Invalid text style!" },
          { quoted: msg }
        );

      const result = await mumaker.ephoto(url, text);
      const imageUrl = result.image || result.imageUrl;

      await sock.sendMessage(
        msg.key.remoteJid,
        {
          image: { url: imageUrl },
          caption: `✨ ${text}\n\nGenerated by 𝐍𝐈𝐆𝐇𝐓-𝐇𝐎𝐖𝐋𝐄𝐑 BOT`,
        },
        { quoted: msg }
      );
    } catch (e) {
      console.error(e);
      await sock.sendMessage(
        msg.key.remoteJid,
        { text: "⚠️ Something went wrong!" },
        { quoted: msg }
      );
    }
  },
};
