export default {
  name: "textmaker",
  description: "Show available textlogo effects and usage help",
  async execute(sock, msg) {
    const from = msg.key.remoteJid;
    const botName = "NexOra";

    // ✅ Use the raw GitHub link so the image loads properly
    const bannerUrl = "https://raw.githubusercontent.com/seniority1/NexOra-files/main/file_00000000f45c61fbab4dc8d5d417130b.png";

    const effectsList = `
🎨 *TEXT LOGO MAKER HELP* 🎨

🧩 *Usage:*  
.textlogo <effect> <text>

📘 *Example:*  
.textlogo fire NexOra

🔥 *Available Effects:*
──────────────────────
🔥 fire        💡 neon
❄️ ice         👹 devil
⚡ thunder     🧠 hacker
🟣 purple      🏖️ sand
💥 glitch      🪴 leaves
🧊 metallic    🎥 1917
🎮 arena       💫 impressive
🕶️ matrix      💡 light
💖 blackpink   ⛄ snow
──────────────────────

⚙️ *Engine:* ephoto360  
🤖 *Bot:* ${botName}  
📌 *Command:* .textlogo <effect> <text>
`;

    await sock.sendMessage(
      from,
      {
        image: { url: bannerUrl },
        caption: effectsList.trim(),
        footer: "Generated by NexOra Bot ⚡",
      },
      { quoted: msg }
    );
  },
};
